# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\"\xb4\x03\n\x07Session\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x13\n\x0brecord_type\x18\x02 \x01(\t\x12\x11\n\tuseragent\x18\x03 \x01(\t\x12\x16\n\x0estates_visited\x18\x04 \x03(\t\x12\x0b\n\x03sid\x18\x05 \x01(\x03\x12\x0b\n\x03uid\x18\x06 \x01(\t\x12\x15\n\ris_subscriber\x18\x07 \x01(\x05\x12\x10\n\x08\x63\x61mpaign\x18\x08 \x01(\t\x12\x0f\n\x07\x63hannel\x18\t \x01(\t\x12\x0e\n\x06gender\x18\n \x01(\t\x12\x0b\n\x03\x61ge\x18\x0b \x01(\t\x12\x10\n\x08latitude\x18\x0c \x01(\x01\x12\x11\n\tlongitude\x18\r \x01(\x01\x12\x12\n\nplace_name\x18\x0e \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x0f \x01(\t\x12\x10\n\x08timezone\x18\x10 \x01(\t\x12\x0c\n\x04home\x18\x11 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x12 \x01(\x05\x12\x11\n\tclickbait\x18\x13 \x01(\x05\x12\x11\n\tsubscribe\x18\x14 \x01(\x05\x12\x13\n\x0bplusContent\x18\x15 \x01(\x05\x12\x15\n\raffiliateLink\x18\x16 \x01(\x05\x12\x13\n\x0b\x65xitSession\x18\x17 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSION']._serialized_start=18
  _globals['_SESSION']._serialized_end=454
# @@protoc_insertion_point(module_scope)
